[alias]
custom-fmt = "fmt -- --config group_imports=StdExternalCrate --config imports_granularity=module"
check-custom-fmt = "fmt -- --check --config group_imports=StdExternalCrate --config imports_granularity=module"
